### ISSUE TITLE
ERR_REQUIRE_ESM

### ISSUE THREAD

**Issue by mobei12** [unjs/webpackbar#140]
### Environment

"webpack": "^5.90.3"
"typescript": "^5.3.3"
"webpackbar": "^6.0.1"
"node": "v18.16.1"

### Reproduction

https://github.com/mobei12/React-ts-webpack

### Describe the bug

when i  try to build or dev the project,i got 
 Error [ERR_REQUIRE_ESM]: require() of ES Module D:\code\initTSWebPack\node_modules\string-width\index.js from D:\code\initTSWebPack\node_modules\wrap-ansi\index.js not supported.
Instead change the require of D:\code\initTSWebPack\node_modules\string-width\index.js in D:\code\initTSWebPack\node_modules\wrap-ansi\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\code\initTSWebPack\node_modules\wrap-ansi\index.js:2:21)
    at Object.<anonymous> (D:\code\initTSWebPack\node_modules\webpackbar\dist\index.cjs:12:18)
    at Object.<anonymous> (D:\code\initTSWebPack\build\webpack.base.js:3:21)
    at Object.<anonymous> (D:\code\initTSWebPack\build\webpack.prod.js:4:20) {
  code: 'ERR_REQUIRE_ESM'

**Comment by mobei12** [comment]
Webpackbar should update the version of the Wrap-ASI version to 9, fixed [Err_require_esm]
