### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by RenataFox** [unjs/webpackbar#95]
I use:

1) nuxtjs 2.15.8
2) node 16.13.1
3) npm 8.2.0

After command npm run dev (cross-env NODE_ENV=development PORT=3333 sails lift):

C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:168
    const str = String(data);
                ^

RangeError: Maximum call stack size exceeded
    at String (<anonymous>)
    at LogUpdate._onData (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:168:17)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:196:14)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:198:44)
    at WriteStream.write (C:\Users\KEY_2_PK\Desktop\repos\ASUBPnew5\node_modules\@nuxt\webpack\node_modules\webpackbar\dist\webpackbar.js:193:25)
    
    How do I fix this error?

**Comment by pi0** [comment]
closing as issue is old. if you could reproduce again please ping to reopen.
